/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontSong32.c                                          *
* Font:        ËÎÌו                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\FontSong16.txt   *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong32;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong32_5B50[132] = { /* code 5B50 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,XX______,
  ______XX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,________,_______X,XXX_____,
  ________,________,______XX,________,
  ________,________,_____XX_,________,
  ________,________,___XX___,________,
  ________,________,__XX____,________,
  ________,_______X,XX______,________,
  ________,_______X,XX______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,___X____,
  ________,_______X,X_______,__XXX___,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,__XXXXXX,X_______,________,
  ________,_____XXX,________,________,
  ________,______X_,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong32_7535[132] = { /* code 7535 */
  ________,________,________,________,
  ________,________,________,________,
  ________,______XX,________,________,
  ________,______XX,X_______,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XX_,______XX,________,X_______,
  _____XX_,______XX,________,________,
  ________,______XX,________,___X____,
  ________,______XX,________,____X___,
  ________,______XX,________,____X___,
  ________,______XX,________,___XX___,
  ________,______XX,X_______,___XXX__,
  ________,_______X,XXXXXXXX,XXXXX___,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong32_77F3[132] = { /* code 77F3 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,___XX___,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,_____XXX,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,___XX___,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,_XX_____,________,X_______,
  ________,_XXXXXXX,XXXXXXXX,XXX_____,
  ________,XXXX____,________,XX______,
  _______X,X_XX____,________,XX______,
  ______XX,__XX____,________,XX______,
  _____XX_,__XX____,________,XX______,
  ____XX__,__XX____,________,XX______,
  ___XX___,__XX____,________,XX______,
  __X_____,__XX____,________,XX______,
  _X______,__XX____,________,XX______,
  ________,__XX____,________,XX______,
  ________,__XX____,________,XX______,
  ________,__XXXXXX,XXXXXXXX,XX______,
  ________,__XX____,________,XX______,
  ________,__XX____,________,XX______,
  ________,__XX____,________,X_______,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong32_786C[132] = { /* code 786C */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,__XX____,________,___XX___,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  _______X,________,_____X__,________,
  ______XX,________,_____X__,________,
  ______XX,________,_____X__,___X____,
  ______XX,______XX,_____X__,___XX___,
  ______X_,______XX,XXXXXXXX,XXXXX___,
  _____XX_,______XX,_____X__,___XX___,
  _____XX_,______XX,_____X__,___XX___,
  _____XXX,XXXXX_XX,_____X__,___XX___,
  ____XXX_,__XX__XX,XXXXXXXX,XXXXX___,
  ____XXX_,__XX__XX,_____X__,___XX___,
  ___XXXX_,__XX__XX,_____X__,___XX___,
  ___X_XX_,__XX__XX,_____X__,___XX___,
  __X__XX_,__XX__XX,_____X__,___XX___,
  _X___XX_,__XX__XX,XXXXXXXX,XXXXX___,
  _____XX_,__XX__XX,_____X__,___XX___,
  _____XX_,__XX___X,____XX__,________,
  _____XX_,__XX___X,____XX__,________,
  _____XX_,__XX____,X___X___,________,
  _____XX_,__XX____,_X_XX___,________,
  _____XXX,XXXX____,__XXX___,________,
  _____XX_,__XX____,__XXX___,________,
  _____XX_,________,_XX_XXX_,________,
  _____XX_,________,XX___XXX,X_______,
  ________,______XX,_______X,XXXXXXX_,
  ________,____XX__,________,_XXXX___,
  ________,_XXX____,________,____X___,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFontSong32_CharInfo[4] = {
   {  32,  32,  4, acGUI_FontFontSong32_5B50 } /* code 5B50 */
  ,{  32,  32,  4, acGUI_FontFontSong32_7535 } /* code 7535 */
  ,{  32,  32,  4, acGUI_FontFontSong32_77F3 } /* code 77F3 */
  ,{  32,  32,  4, acGUI_FontFontSong32_786C } /* code 786C */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong32_Prop4 = {
   0x786C /* first character */
  ,0x786C /* last character  */
  ,&GUI_FontFontSong32_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong32_Prop3 = {
   0x77F3 /* first character */
  ,0x77F3 /* last character  */
  ,&GUI_FontFontSong32_CharInfo[  2] /* address of first character */
  ,&GUI_FontFontSong32_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong32_Prop2 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontFontSong32_CharInfo[  1] /* address of first character */
  ,&GUI_FontFontSong32_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong32_Prop1 = {
   0x5B50 /* first character */
  ,0x5B50 /* last character  */
  ,&GUI_FontFontSong32_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontSong32_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong32 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontSong32_Prop1}
  ,27 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

